# FILE: cli/main.py
#!/usr/bin/env python3
"""
Probaah CLI - Main entry point
Where research flows naturally (প্ৰবাহ)
"""

import click
import os
import yaml
from datetime import datetime
from pathlib import Path
from rich.console import Console
from rich.table import Table

console = Console()

@click.group()
@click.version_option(version="1.0.0")
def cli():
    """🌊 Probaah - Where research flows naturally"""
    console.print("🌊 [bold blue]Probaah[/bold blue] (প্ৰবাহ) - Automated Research Workflows", style="bold")

@cli.group()
def project():
    """Project management commands"""
    pass

@cli.group()
def jobs():
    """SLURM job management commands"""
    pass

@cli.group()
def config():
    """Configuration management"""
    pass

@project.command("create")
@click.argument("name")
@click.option("--type", default="reaxff", help="Project type (reaxff, gaussian, ams)")
@click.option("--description", default="", help="Project description")
def create_project(name, type, description):
    """Create a new organized research project"""
    
    # Create project directory with timestamp
    timestamp = datetime.now().strftime("%Y%m%d")
    project_dir = f"{name}_{timestamp}"
    
    # Standard directory structure
    directories = [
        "input_files/templates",
        "input_files/current", 
        "input_files/archive",
        "job_scripts/slurm_templates",
        "job_scripts/active_jobs",
        "job_scripts/completed_jobs",
        "trajectories/raw",
        "trajectories/processed",
        "trajectories/videos",
        "analysis/scripts",
        "analysis/results",
        "analysis/figures",
        "notes/daily_logs",
        "notes/observations"
    ]
    
    console.print(f"🚀 Creating project: [bold]{project_dir}[/bold]")
    
    try:
        # Create directories
        for dir_path in directories:
            full_path = Path(project_dir) / dir_path
            full_path.mkdir(parents=True, exist_ok=True)
        
        # Create README.md
        readme_content = f"""# {name}

**Created**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Type**: {type}
**Description**: {description or "Research project created with Probaah"}

## Project Structure

- `input_files/` - Simulation input files
- `job_scripts/` - SLURM job scripts  
- `trajectories/` - Simulation outputs
- `analysis/` - Data analysis and results
- `notes/` - Research notes and observations

## Quick Commands

```bash
# Submit a job
probaah jobs submit input_files/current/simulation.xyz

# Check job status
probaah jobs status

# Add daily note
probaah project note "Today I worked on..."
```

---
*Generated by Probaah (প্ৰবাহ) - Where research flows naturally*
"""
        
        with open(Path(project_dir) / "README.md", "w") as f:
            f.write(readme_content)
        
        # Create project config
        config = {
            "project": {
                "name": name,
                "type": type,
                "created": datetime.now().isoformat(),
                "description": description
            },
            "settings": {
                "auto_backup": True,
                "email_notifications": True,
                "git_tracking": True
            }
        }
        
        with open(Path(project_dir) / ".probaah-config.yaml", "w") as f:
            yaml.dump(config, f, default_flow_style=False)
        
        # Initialize git repository
        os.chdir(project_dir)
        os.system("git init")
        os.system("git add .")
        os.system(f'git commit -m "Initial project setup with Probaah"')
        os.chdir("..")
        
        console.print(f"✅ Project created successfully!")
        console.print(f"📁 Location: [bold]{os.path.abspath(project_dir)}[/bold]")
        console.print(f"🎯 Next: cd {project_dir}")
        
    except Exception as e:
        console.print(f"❌ Error creating project: {e}", style="red")

@project.command("list")
def list_projects():
    """List all Probaah projects in current directory"""
    
    projects = []
    for item in os.listdir("."):
        if os.path.isdir(item) and os.path.exists(f"{item}/.probaah-config.yaml"):
            try:
                with open(f"{item}/.probaah-config.yaml", "r") as f:
                    config = yaml.safe_load(f)
                    projects.append({
                        "name": config["project"]["name"],
                        "type": config["project"]["type"],
                        "created": config["project"]["created"][:10],  # Just date
                        "folder": item
                    })
            except:
                continue
    
    if not projects:
        console.print("No Probaah projects found in current directory")
        console.print("Create one with: [bold]probaah project create my-project[/bold]")
        return
    
    table = Table(title="🌊 Probaah Projects")
    table.add_column("Name", style="cyan")
    table.add_column("Type", style="green")
    table.add_column("Created", style="yellow")
    table.add_column("Folder", style="blue")
    
    for project in projects:
        table.add_row(
            project["name"],
            project["type"],
            project["created"],
            project["folder"]
        )
    
    console.print(table)

@project.command("status")
def project_status():
    """Show current project status"""
    
    if not os.path.exists(".probaah-config.yaml"):
        console.print("❌ Not in a Probaah project directory", style="red")
        console.print("Run this command from inside a project folder")
        return
    
    try:
        with open(".probaah-config.yaml", "r") as f:
            config = yaml.safe_load(f)
        
        console.print(f"📊 [bold]Project Status[/bold]")
        console.print(f"Name: {config['project']['name']}")
        console.print(f"Type: {config['project']['type']}")
        console.print(f"Created: {config['project']['created'][:10]}")
        
        # Count files in different directories
        stats = {}
        for dir_name in ["input_files", "job_scripts", "trajectories", "analysis"]:
            if os.path.exists(dir_name):
                count = sum([len(files) for r, d, files in os.walk(dir_name)])
                stats[dir_name] = count
        
        console.print("\n📁 [bold]Directory Contents[/bold]")
        for dir_name, count in stats.items():
            console.print(f"{dir_name}: {count} files")
        
    except Exception as e:
        console.print(f"❌ Error reading project status: {e}", style="red")

@jobs.command("status")
@click.option("--user", default="akp6421", help="Cluster username")
def job_status(user):
    """Check SLURM job status on cluster"""
    
    console.print(f"🔍 Checking jobs for user: [bold]{user}[/bold]")
    
    try:
        import paramiko
        
        # SSH connection (simplified for now)
        # In production, this would use stored SSH keys
        console.print("🔐 Connecting to Roar Collab...")
        console.print("ℹ️  SSH key authentication required")
        console.print("💡 Run: probaah config ssh --setup for first-time setup")
        
        # For now, just show the command they can run manually
        console.print("\n📋 [bold]Manual Check:[/bold]")
        console.print(f"ssh {user}@submit.aci.ics.psu.edu 'squeue -u {user}'")
        
    except ImportError:
        console.print("📦 Installing paramiko for SSH functionality...")
        os.system("pip install paramiko")
        console.print("✅ Please run the command again")

@config.command("init")
@click.option("--user", default="anirban", help="Your name")
@click.option("--email", default="", help="Your email")
@click.option("--cluster", default="roar_collab", help="Default cluster")
def init_config(user, email, cluster):
    """Initialize Probaah configuration"""
    
    console.print("🔧 [bold]Setting up Probaah configuration[/bold]")
    
    # Create config directory
    config_dir = Path.home() / ".probaah"
    config_dir.mkdir(exist_ok=True)
    
    # Create user profile
    profile = {
        "user": {
            "name": user,
            "email": email or f"{user}@psu.edu",
            "created": datetime.now().isoformat()
        },
        "clusters": {
            "roar_collab": {
                "hostname": "submit.aci.ics.psu.edu",
                "username": "akp6421",  # Default, can be changed
                "default_partition": "open",
                "max_time": "168:00:00"
            }
        },
        "settings": {
            "auto_backup": True,
            "email_notifications": False,  # Will enable after setup
            "default_project_type": "reaxff"
        }
    }
    
    config_file = config_dir / "user_profile.yaml"
    with open(config_file, "w") as f:
        yaml.dump(profile, f, default_flow_style=False)
    
    console.print(f"✅ Configuration saved to: [bold]{config_file}[/bold]")
    console.print("🎯 Next steps:")
    console.print("  1. probaah config ssh --setup")
    console.print("  2. probaah project create my-first-project")

@config.command("show")
def show_config():
    """Show current configuration"""
    
    config_file = Path.home() / ".probaah" / "user_profile.yaml"
    
    if not config_file.exists():
        console.print("❌ No configuration found", style="red")
        console.print("Run: [bold]probaah config init[/bold]")
        return
    
    try:
        with open(config_file, "r") as f:
            config = yaml.safe_load(f)
        
        console.print("⚙️  [bold]Current Configuration[/bold]")
        console.print(f"User: {config['user']['name']}")
        console.print(f"Email: {config['user']['email']}")
        console.print(f"Default cluster: {list(config['clusters'].keys())[0]}")
        
    except Exception as e:
        console.print(f"❌ Error reading config: {e}", style="red")

# Add new command groups for analysis and presentation
@cli.group()
def analyze():
    """Advanced analysis with ASE and scientific tools"""
    pass

@cli.group()
def presentation():
    """Automated presentation generation"""
    pass

@cli.group()
def render():
    """Visualization and rendering tools"""
    pass

# Analysis commands
@analyze.command("trajectory")
@click.argument("trajectory_file")
@click.option("--output-dir", default=None, help="Output directory")
@click.option("--bonds/--no-bonds", default=True, help="Analyze bonds")
@click.option("--rdf/--no-rdf", default=True, help="Calculate RDF")
@click.option("--energy/--no-energy", default=True, help="Analyze energy")
@click.option("--plots/--no-plots", default=True, help="Generate plots")
def analyze_trajectory(trajectory_file, output_dir, bonds, rdf, energy, plots):
    """Comprehensive trajectory analysis using ASE"""
    try:
        # Import the analyzer
        import sys
        sys.path.append('plugins/analysis/ase_tools')
        from trajectory_analyzer import analyze_trajectory_cli
        
        console.print(f"🔬 [bold]Analyzing trajectory:[/bold] {trajectory_file}")
        
        results = analyze_trajectory_cli(
            trajectory_file=trajectory_file,
            output_dir=output_dir,
            bonds=bonds,
            rdf=rdf,
            energy=energy,
            plots=plots
        )
        
        console.print("✅ [bold green]Analysis complete![/bold green]")
        
        # Show summary
        if bonds and 'bonds' in results:
            console.print(f"📊 Average bonds: {results['bonds']['avg_count']:.1f}")
        
        if output_dir:
            console.print(f"📁 Results saved to: [bold]{output_dir}[/bold]")
            
    except ImportError as e:
        console.print(f"❌ [red]Error importing analyzer: {e}[/red]")
        console.print("💡 Make sure all dependencies are installed: pip install ase matplotlib")
    except Exception as e:
        console.print(f"❌ [red]Analysis failed: {e}[/red]")

@analyze.command("bonds")
@click.argument("trajectory_file")
@click.option("--cutoff", default=1.2, help="Bond cutoff factor")
@click.option("--output", default="bond_analysis.png", help="Output plot file")
def analyze_bonds_only(trajectory_file, cutoff, output):
    """Quick bond analysis only"""
    try:
        import sys
        sys.path.append('plugins/analysis/ase_tools')
        from trajectory_analyzer import ProbaahTrajectoryAnalyzer
        
        console.print(f"🔗 [bold]Bond analysis:[/bold] {trajectory_file}")
        
        analyzer = ProbaahTrajectoryAnalyzer(trajectory_file)
        results = analyzer.analyze_bonds(cutoff_factor=cutoff)
        plots = analyzer.create_plots()
        
        console.print(f"✅ Average bonds: {results['avg_count']:.1f}")
        console.print(f"📊 Plot saved: {plots.get('bond_evolution', 'bond_evolution.png')}")
        
    except Exception as e:
        console.print(f"❌ [red]Bond analysis failed: {e}[/red]")

# Presentation commands
@presentation.command("create")
@click.argument("analysis_dir")
@click.option("--title", default="Research Update", help="Presentation title")
@click.option("--output", default="presentation.pptx", help="Output PowerPoint file")
@click.option("--style", default="weekly", help="Presentation style")
def create_presentation(analysis_dir, title, output, style):
    """Create automated research presentation"""
    try:
        import sys
        sys.path.append('plugins/presentation/pptx_generator')
        from research_slides import generate_presentation_cli
        
        console.print(f"🎨 [bold]Creating presentation:[/bold] {title}")
        
        output_file = generate_presentation_cli(
            analysis_dir=analysis_dir,
            title=title,
            output=output,
            style=style
        )
        
        console.print(f"✅ [bold green]Presentation created:[/bold green] {output_file}")
        console.print("💡 Open in PowerPoint to view and edit")
        
    except ImportError as e:
        console.print(f"❌ [red]Error importing presentation generator: {e}[/red]")
        console.print("💡 Make sure python-pptx is installed: pip install python-pptx")
    except Exception as e:
        console.print(f"❌ [red]Presentation creation failed: {e}[/red]")

@presentation.command("weekly")
@click.option("--project-dir", default=".", help="Project directory")
@click.option("--title", default=None, help="Custom title")
def weekly_update(project_dir, title):
    """Generate weekly update presentation from current project"""
    try:
        import os
        from datetime import datetime
        
        # Check if we're in a Probaah project
        if not os.path.exists(".probaah-config.yaml"):
            console.print("❌ [red]Not in a Probaah project directory[/red]")
            console.print("💡 Run this from inside a project folder")
            return
        
        # Look for analysis directory
        analysis_dirs = ["analysis", "trajectories/processed", "."]
        analysis_dir = None
        for d in analysis_dirs:
            if os.path.exists(os.path.join(d, "analysis_results.json")):
                analysis_dir = d
                break
        
        if not analysis_dir:
            console.print("❌ [red]No analysis results found[/red]")
            console.print("💡 Run 'probaah analyze trajectory your_file.xyz' first")
            return
        
        # Generate presentation
        if not title:
            project_name = os.path.basename(os.getcwd())
            title = f"{project_name} - Weekly Update"
        
        date_str = datetime.now().strftime("%Y%m%d")
        output_file = f"weekly_update_{date_str}.pptx"
        
        import sys
        sys.path.append('plugins/presentation/pptx_generator')
        from research_slides import create_weekly_update_presentation
        
        result = create_weekly_update_presentation(analysis_dir, output_file, title)
        console.print(f"✅ [bold green]Weekly update created:[/bold green] {result}")
        
    except Exception as e:
        console.print(f"❌ [red]Weekly update failed: {e}[/red]")

# Rendering commands
@render.command("trajectory")
@click.argument("trajectory_file")
@click.option("--output", default="trajectory.mp4", help="Output video file")
@click.option("--frames", default=10, help="Number of frames to render")
@click.option("--style", default="publication", help="Rendering style")
def render_trajectory(trajectory_file, output, frames, style):
    """Render trajectory as video using ASE"""
    try:
        import sys
        sys.path.append('plugins/analysis/ase_tools')
        from ase.io import read
        from ase.visualize.plot import plot_atoms
        import matplotlib.pyplot as plt
        import matplotlib.animation as animation
        
        console.print(f"🎬 [bold]Rendering trajectory:[/bold] {trajectory_file}")
        
        # Load trajectory
        traj = read(trajectory_file, index=f'::{len(read(trajectory_file, index=":"))//frames}')
        
        # Create animation
        fig, ax = plt.subplots(figsize=(10, 8))
        
        def animate(frame):
            ax.clear()
            plot_atoms(traj[frame], ax=ax, radii=0.5)
            ax.set_title(f"Frame {frame}")
            return ax,
        
        anim = animation.FuncAnimation(fig, animate, frames=len(traj), 
                                     interval=200, blit=False)
        
        # Save as MP4
        Writer = animation.writers['ffmpeg']
        writer = Writer(fps=5, metadata=dict(artist='Probaah'), bitrate=1800)
        anim.save(output, writer=writer)
        
        console.print(f"✅ [bold green]Video saved:[/bold green] {output}")
        
    except Exception as e:
        console.print(f"❌ [red]Rendering failed: {e}[/red]")
        console.print("💡 Note: Video rendering requires ffmpeg")

# Quick workflow command
@cli.command("workflow")
@click.argument("trajectory_file")
@click.option("--title", default="Analysis Results", help="Presentation title")
def full_workflow(trajectory_file, title):
    """Complete analysis + presentation workflow"""
    console.print("🚀 [bold blue]Running complete Probaah workflow![/bold blue]")
    
    # Step 1: Analysis
    console.print("\n📊 Step 1: Trajectory Analysis")
    try:
        import sys
        sys.path.append('plugins/analysis/ase_tools')
        from trajectory_analyzer import analyze_trajectory_cli
        
        results = analyze_trajectory_cli(trajectory_file, bonds=True, rdf=True, energy=True, plots=True)
        console.print("✅ Analysis complete")
        
    except Exception as e:
        console.print(f"❌ Analysis failed: {e}")
        return
    
    # Step 2: Presentation
    console.print("\n🎨 Step 2: Presentation Generation")
    try:
        import sys
        sys.path.append('plugins/presentation/pptx_generator')
        from research_slides import create_weekly_update_presentation
        
        analysis_dir = Path(trajectory_file).parent / "analysis"
        output_file = f"{title.replace(' ', '_')}_presentation.pptx"
        
        create_weekly_update_presentation(str(analysis_dir), output_file, title)
        console.print("✅ Presentation created")
        
    except Exception as e:
        console.print(f"❌ Presentation failed: {e}")
    
    console.print(f"\n🎉 [bold green]Workflow complete![/bold green]")
    console.print("📁 Check the analysis/ directory for results")
    console.print(f"📊 Open {output_file} for presentation")

# Entry point for pip installation
def main():
    cli()

if __name__ == "__main__":
    main()
